connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://iceberg_rest:8181/api/catalog
iceberg.rest-catalog.warehouse=s3://iceberg-catalog





fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.aws-access-key=qOFclq6eGlFnjm18lIEc
s3.aws-secret-key=T3Wd9h3CjUe9pcRF0DakmrjTBDWYUmDGA9Wue5X0
s3.region=us-east-1
s3.path-style-access=true
